c_compiler:
  - gcc # [linux]
  - clang # [osx]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
fortran_compiler:
  - gfortran # [osx]
CONDA_BUILD_SYSROOT:
  - /opt/SDK/10.9SDK/MacOSX10.9.sdk  # [osx]
