c_compiler:
  - gcc # [linux]
  - clang # [osx]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
fortran_compiler:
  - gfortran # [osx]
CONDA_BUILD_SYSROOT:
  #- /opt/MacOSX10.9.sdk  # [osx]
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk # [osx]
#numpy:
#  - 1.20\
